# Site settings
title: Days in Life
email: ridwan.arefin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Kazi Ridwan's blog.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "https://kaziridwan.github.io" # the base hostname & protocol for your site
twitter_username: ridwanshere
github_username:  kaziridwan

# Build settings
markdown: kramdown

paginate: 4

author: Ridwan

gems: [jekyll-paginate]
