# Site settings
title: Teaway
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  De la feuille à la liqueur... un moment de relaxation.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ash45.github.io" # the base hostname & protocol for your site
twitter_username: teaway
github_username:  Ash45

# Build settings
markdown: kramdown

paginate: 4

author: Ash45

gems: [jekyll-paginate]

theme: jekyll-theme-cayman